#!/usr/bin/env bash
# HAProxy configuration for redirecting HTTP to HTTPS

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.yourdomain.com/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

frontend www-http
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }

backend www-backend
    server webserver1 52.86.74.62:80 check
    server webserver2 100.25.192.229:80 check
