#!/usr/bin/env bash
# transfering file to the server

file="$1"
username="$3"
ip="$2"
path="$4"

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
scp -i $path" "$file" "$username@$ip:~/ 
