#!/usr/bin/env bash
# This script installs and configures HAproxy on lb-01 server to distribute traffic to web-01 and web-02 using roundrobin algorithm

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup  # Backup the original configuration file

# Create a new HAproxy configuration file
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 530678-web-01 52.86.74.62:80 check
    server web02 530678-web-02 100.25.192.229:80 check
EOL

# Restart HAproxy service
sudo systemctl restart haproxy

