#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 and restarts the service

# Update Nginx configuration to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Check if Nginx configuration syntax is correct
sudo nginx -t

# Restart Nginx service
sudo systemctl restart nginx
