#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

sed -i 's/user www-data;/user nginx/' /etc/nginx/nginx.conf
echo "listen 8080 default_server;" >> /etc/nginx/sites-available/default
nginx -s reload

